# This file tells Google Cloud Build how to deploy the application.
# It can be attached to a variety of triggers, the default being whenever
# someone merges changes to the `master` branch.
steps:
# Build the proxy
- id: 'proxy.pull'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: '/bin/bash'
  args: [
    '-c',
    'docker pull gcr.io/$PROJECT_ID/$REPO_NAME-proxy:latest || exit 0'
  ]
  waitFor: [ '-' ]
- id: 'proxy.build'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-proxy:latest',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-proxy:$COMMIT_SHA',
    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME-proxy:latest',
    '.',
    '--build-arg', 'CONF_FILE=prod.conf'
  ]
  waitFor: [ 'proxy.pull' ]
  dir: 'proxy'
- id: 'proxy.push'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/$REPO_NAME-proxy:$COMMIT_SHA'
  ]
  waitFor: [ 'proxy.build' ]
# Build the Python application
- id: 'app.pull'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: '/bin/bash'
  args: [
    '-c',
    'docker pull gcr.io/$PROJECT_ID/$REPO_NAME-app:latest || exit 0'
  ]
  waitFor: [ '-' ]
- id: 'app.build'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-app:latest',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-app:$COMMIT_SHA',
    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME-app:latest',
    '.',
    '--build-arg', 'FLASK_ENV=production'
  ]
  waitFor: [ 'app.pull' ]
  dir: 'app'
- id: 'app.push'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/$REPO_NAME-app:$COMMIT_SHA',
  ]
  waitFor: [ 'app.build' ]
# Generate our Kubernetes configuration
- id: 'config'
  name: 'gcr.io/ai2-reviz/jsonnet'
  args: [
    'eval',
    '-y',
    '--output-file', './webapp.yaml',
    '--tla-str', 'env=$_ENV',
    '--tla-str', 'appImage=gcr.io/$PROJECT_ID/$REPO_NAME-app:$COMMIT_SHA',
    '--tla-str', 'proxyImage=gcr.io/$PROJECT_ID/$REPO_NAME-proxy:$COMMIT_SHA',
    '--tla-str', 'sha=$COMMIT_SHA',
    '--tla-str', 'cause=Automated Skiff Deploy SHA:$COMMIT_SHA BUILD:$BUILD_ID',
    '--tla-str', 'branch=$BRANCH_NAME',
    '--tla-str', 'repo=$REPO_NAME',
    '--tla-str', 'buildId=$BUILD_ID',
    './webapp.jsonnet'
  ]
  dir: '.skiff'
# Deploy the image to Kubernetes
- id: 'deploy'
  name: 'gcr.io/ai2-reviz/rudder'
  args: [
    'deploy',
    '-f',
    'webapp.yaml'
  ]
  dir: '.skiff'
substitutions:
  _ENV: staging
images: [
  'gcr.io/$PROJECT_ID/$REPO_NAME-app:$COMMIT_SHA',
  'gcr.io/$PROJECT_ID/$REPO_NAME-app:latest',
  'gcr.io/$PROJECT_ID/$REPO_NAME-proxy:$COMMIT_SHA',
  'gcr.io/$PROJECT_ID/$REPO_NAME-proxy:latest'
]
artifacts:
  objects:
    location: 'gs://skiff-archive/$REPO_NAME/$_ENV/$BUILD_ID/$COMMIT_SHA'
    paths: ['.skiff/webapp.yaml']
