name: CI

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  check_configs:
    name: Check Configs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Check configs
      run: |
        python app/app/projects.py
